### PR TITLE
Bump to angular 18

### PR DESCRIPTION
**Pull request by mperezd**
Bump dependencies to angular 18.

### CODE REVIEW

**Comment by jmtimper** [comment]
👀

**Comment by Jaga-1267** [comment]
Hi, May I know when this PR can get merged?

**Comment by Jaga-1267** [comment]
Hi @raysuelzer, Can you please make this library to be compatible with angular 18 asap.

**Comment by raysuelzer** [comment]
@mperezd Do you want to be a contributor to this project? Also, the real version you need to update in the package.json is under projects/ngx-angular-query-builder   that is what is actually published to npm.

**Comment by mperezd** [comment]
> @mperezd Do you want to be a contributor to this project? Also, the real version you need to update in the package.json is under projects/ngx-angular-query-builder that is what is actually published to npm.

@raysuelzer I'll take that into account next time we need to update it. Add me as a contributor if you want, I'll try to do my best.

**Pull request merged**
